### ISSUE TITLE
使用dynamic-tp-spring-boot-starter-adapter-dubbo报错

### ISSUE THREAD

**Issue by akun4515** [dromara/dynamic-tp#132]
**首先感谢您使用 DynamicTp，如果使用过程中有任何问题，请按照下述模板反馈问题，建议使用 Markdown 语法**。

### 版本信息

- JDK版本 1.8：
- springBoot版本 2.5.8：
- dynamic-tp-spring-boot-starter-apollo 1.1.0：
- apollo 1.3.0：

### 问题描述

使用dynamic-tp-spring-boot-starter-adapter-dubbo 1.1.0 启动之后报错

2023-02-13 18:02:24 CST ERROR com.dtp.adapter.common.AbstractDtpAdapter main 60 onApplicationEvent - Init third party thread pool failed. java.util.ConcurrentModificationException: null
	at java.util.HashMap.forEach(HashMap.java:1291) ~[?:1.8.0_131]
	at com.dtp.adapter.dubbo.alibaba.AlibabaDubboDtpAdapter.initialize(AlibabaDubboDtpAdapter.java:41) ~[dynamic-tp-adapter-dubbo-1.1.0.jar:1.1.0]
	at com.dtp.adapter.common.AbstractDtpAdapter.onApplicationEvent(AbstractDtpAdapter.java:57) ~[dynamic-tp-adapter-common-1.1.0.jar:1.1.0]
	at com.dtp.adapter.common.AbstractDtpAdapter.onApplicationEvent(AbstractDtpAdapter.java:46) ~[dynamic-tp-adapter-common-1.1.0.jar:1.1.0]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.14.jar:5.3.14]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.14.jar:5.3.14]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.14.jar:5.3.14]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) ~[spring-context-5.3.14.jar:5.3.14]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-5.3.14.jar:5.3.14]
	at org.springframework.boot.context.event.EventPublishingRunListener.running(EventPublishingRunListener.java:111) ~[spring-boot-2.5.8.jar:2.5.8]
	at org.springframework.boot.SpringApplicationRunListeners.lambda$running$6(SpringApplicationRunListeners.java:79) ~[spring-boot-2.5.8.jar:2.5.8]
	at java.util.ArrayList.forEach(ArrayList.java:1249) [?:1.8.0_131]
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117) [spring-boot-2.5.8.jar:2.5.8]
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111) [spring-boot-2.5.8.jar:2.5.8]
	at org.springframework.boot.SpringApplicationRunListeners.running(SpringApplicationRunListeners.java:79) [spring-boot-2.5.8.jar:2.5.8]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:353) [spring-boot-2.5.8.jar:2.5.8]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354) [spring-boot-2.5.8.jar:2.5.8]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) [spring-boot-2.5.8.jar:2.5.8]
	at cn.dface.biz.im.web.api.ImWebApiApplication.main(ImWebApiApplication.java:29) [classes/:?]

**Comment by yanhom1314** [comment]
是个bug，下版本修复
