### ISSUE TITLE
使用dynamic-tp-spring-boot-starter-adapter-webserver启动报错

### ISSUE THREAD

**Issue by 754466488** [dromara/dynamic-tp#148]
**首先感谢您使用 DynamicTp，如果使用过程中有任何问题，请按照下述模板反馈问题，建议使用 Markdown 语法**。

### 版本信息

- Jdk版本：1.8
- SpringBoot版本：2.2.5.RELEASE
- DynamicTp版本：1.1.0
- nacos版本：0.2.7

### 问题描述

项目使用undertow作为容器服务器，引入dynamic-tp-spring-boot-starter-adapter-webserver项目启动报错，错误如下：

java.lang.ClassCastException: org.springframework.boot.web.embedded.undertow.UndertowServletWebServer cannot be cast to org.springframework.boot.web.embedded.undertow.UndertowWebServer
	at com.dtp.adapter.webserver.UndertowDtpAdapter.doGetExecutorWrapper(UndertowDtpAdapter.java:44) ~[dynamic-tp-adapter-webserver-1.1.0.jar:1.1.0]
	at com.dtp.adapter.webserver.AbstractWebServerDtpAdapter.initialize(AbstractWebServerDtpAdapter.java:57) [dynamic-tp-adapter-webserver-1.1.0.jar:1.1.0]
	at com.dtp.adapter.webserver.AbstractWebServerDtpAdapter.onApplicationEvent(AbstractWebServerDtpAdapter.java:36) [dynamic-tp-adapter-webserver-1.1.0.jar:1.1.0]
	at com.dtp.adapter.webserver.AbstractWebServerDtpAdapter.onApplicationEvent(AbstractWebServerDtpAdapter.java:26) [dynamic-tp-adapter-webserver-1.1.0.jar:1.1.0]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) [spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) [spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) [spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:404) [spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:361) [spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:165) [spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:554) [spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) [spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) [spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at com.dzw.dynamic.DynamicApplication.main(DynamicApplication.java:12) [classes/:na]

<img width="848" alt="image" src="https://user-images.githubusercontent.com/23232437/220862291-936228d9-e2d1-4cb2-9f0a-8df911855cb3.png">

<img width="1195" alt="image" src="https://user-images.githubusercontent.com/23232437/220862394-003b5113-5009-45ae-997e-d141fb0a75d0.png">

**Comment by yanhom1314** [comment]
![image](https://user-images.githubusercontent.com/13051908/220893546-697114fb-034a-47b0-9ce9-de55f24e19c9.png)
![image](https://user-images.githubusercontent.com/13051908/220893580-48d57b41-4e82-4ea4-b4e5-adb8b21a4493.png)
高低版本不兼容问题导致

**Comment by yanhom1314** [comment]
1.1.1版本发布会修复
