### ISSUE TITLE
org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@xxxx has been closed already

### ISSUE THREAD

**Issue by ruoan777** [dromara/dynamic-tp#149]
**首先感谢您使用 DynamicTp，如果使用过程中有任何问题，请按照下述模板反馈问题，建议使用 Markdown 语法**。

### 版本信息

- Jdk版本：1.8
- SpringBoot版本：1.5.9.RELEASE
- DynamicTp版本：1.1.0(但其实基于这个版本做了一些降级，以适配公司的版本)
- 配置中心版本：自研配置中心

### 问题描述
生产上突然有这样的error日志，报错堆栈如下，请问具体是什么原因，有没有办法可以降级？
```
thread Thread[dtp-alarm2,5,main] throw exception {}
java.lang.IllegalStateException: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@48e4ada7 has been closed already
	at org.springframework.context.support.AbstractApplicationContext.assertBeanFactoryActive(AbstractApplicationContext.java:1065)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1092)
	at com.dtp.common.ApplicationContextHolder.getBean(ApplicationContextHolder.java:27)
	at com.dtp.core.notify.manager.AlarmManager.doAlarm(AlarmManager.java:131)
	at com.dtp.core.notify.manager.AlarmManager.lambda$doAlarm$2(AlarmManager.java:116)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at com.dtp.core.notify.manager.AlarmManager.doAlarm(AlarmManager.java:116)
	at com.dtp.core.notify.manager.AlarmManager.doAlarm(AlarmManager.java:112)
	at com.dtp.core.monitor.DtpMonitor.lambda$null$2(DtpMonitor.java:78)
	at com.dianping.cat.async.CatWrappedRunnable.lambda$run$0(CatWrappedRunnable.java:30)
	at com.dianping.cat.async.CatAsyncSupportTemplate.doExecute4Simple(CatAsyncSupportTemplate.java:147)
	at com.dianping.cat.async.CatAsyncSupportTemplate.execute(CatAsyncSupportTemplate.java:94)
	at com.dianping.cat.async.CatWrappedRunnable.run(CatWrappedRunnable.java:29)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

- 配置文件：
- 代码使用步骤：
- 报错信息：
- 猜测可能原因：当时机器有重启，怀疑和这个有关系。查询了一些文档，[这里说 spring application has been stopped](https://stackoverflow.com/questions/57185023/illegalstateexception-org-springframework-boot-context-embedded-annotationconfi) ，不知道是否是这个原因。

**Comment by yanhom1314** [comment]
感觉这个异常正常，异步线程池里用到了一个被spring容器销毁的bean
