### ISSUE TITLE
拉取spring线程池ThreadPoolTaskExecutor，出现GenericBeanDefinition cannot be cast to AnnotatedBeanDefinition 报错

### ISSUE THREAD

**Issue by JiBinXiao** [dromara/dynamic-tp#158]
**首先感谢您使用 DynamicTp，如果对项目有任何疑问需要解答，请按照下述模板提问，建议使用 Markdown 语法**。
spring版本：5.3.14
spring-boot版本：2.5.8

### 使用方面
<img width="1210" alt="image" src="https://user-images.githubusercontent.com/30405636/221855911-5af76195-bfbb-439f-9805-d9e7976e6225.png">
<img width="1213" alt="image" src="https://user-images.githubusercontent.com/30405636/221855943-a338e0a9-3bcf-41cd-a610-5373ff79a88e.png">

报错信息如下：
`Caused by: java.lang.ClassCastException: org.springframework.beans.factory.support.GenericBeanDefinition cannot be cast to org.springframework.beans.factory.annotation.AnnotatedBeanDefinition
 at com.dtp.core.spring.DtpPostProcessor.postProcessAfterInitialization(DtpPostProcessor.java:60)
 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:455)
 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1808)
 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)`

### 其他

**Comment by yanhom1314** [comment]
感谢反馈，这块需要校验下，非AnnotatedBeanDefinition的bean就不处理
