### ISSUE TITLE
bug 单元测试不通过

### ISSUE THREAD

**Issue by ruoan777** [dromara/dynamic-tp#206]
**首先感谢您使用 DynamicTp，如果使用过程中有任何问题，请按照下述模板反馈问题，建议使用 Markdown 语法**。

### 版本信息
1.1.2
### 问题描述

master分支的单元测试不通过，哪位大佬可以修一下。
```
Running com.dtp.test.core.parse.JsonConfigParserTest
Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running com.dtp.test.core.parse.PropertiesConfigParserTest
Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running com.dtp.test.core.thread.DtpExecutorTest
00:46:52.485 [main] ERROR com.dtp.core.DtpRegistry - Cannot find a specified dtpExecutor, name: testRunTimeoutDtpExecutor
00:46:52.491 [main] ERROR com.dtp.core.DtpRegistry - Cannot find a specified dtpExecutor, name: testQueueTimeoutDtpExecutor
00:46:52.491 [main] ERROR com.dtp.core.DtpRegistry - Cannot find a specified dtpExecutor, name: testRejectedQueueTimeoutCancelDtpExecutor
Tests run: 3, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 0.016 sec <<< FAILURE!
com.dtp.test.core.thread.DtpExecutorTest.testRunTimeout()  Time elapsed: 0.013 sec  <<< FAILURE!
com.dtp.common.ex.DtpException: Cannot find a specified dtpExecutor, name: testRunTimeoutDtpExecutor
	at com.dtp.core.DtpRegistry.getDtpExecutor(DtpRegistry.java:119)
	at com.dtp.test.core.thread.DtpExecutorTest.testRunTimeout(DtpExecutorTest.java:50)
com.dtp.test.core.thread.DtpExecutorTest.testQueueTimeout()  Time elapsed: 0 sec  <<< FAILURE!
com.dtp.common.ex.DtpException: Cannot find a specified dtpExecutor, name: testQueueTimeoutDtpExecutor
	at com.dtp.core.DtpRegistry.getDtpExecutor(DtpRegistry.java:119)
	at com.dtp.test.core.thread.DtpExecutorTest.testQueueTimeout(DtpExecutorTest.java:63)
com.dtp.test.core.thread.DtpExecutorTest.testRejectedQueueTimeoutCancel()  Time elapsed: 0 sec  <<< FAILURE!
com.dtp.common.ex.DtpException: Cannot find a specified dtpExecutor, name: testRejectedQueueTimeoutCancelDtpExecutor
	at com.dtp.core.DtpRegistry.getDtpExecutor(DtpRegistry.java:119)
	at com.dtp.test.core.thread.DtpExecutorTest.testRejectedQueueTimeoutCancel(DtpExecutorTest.java:76)
Running com.dtp.test.core.thread.DtpExecutorBenchmarkTest
Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running com.dtp.test.core.thread.ScheduledDtpExecutorTest
00:46:52.493 [main] ERROR com.dtp.core.DtpRegistry - Cannot find a specified dtpExecutor, name: dtpExecutor13
00:46:52.493 [main] ERROR com.dtp.core.DtpRegistry - Cannot find a specified dtpExecutor, name: dtpExecutor14
Tests run: 2, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0 sec <<< FAILURE!
com.dtp.test.core.thread.ScheduledDtpExecutorTest.testScheduleJre8Bug()  Time elapsed: 0 sec  <<< FAILURE!
com.dtp.common.ex.DtpException: Cannot find a specified dtpExecutor, name: dtpExecutor13
	at com.dtp.core.DtpRegistry.getDtpExecutor(DtpRegistry.java:119)
	at com.dtp.test.core.thread.ScheduledDtpExecutorTest.testScheduleJre8Bug(ScheduledDtpExecutorTest.java:40)
com.dtp.test.core.thread.ScheduledDtpExecutorTest.testSubNotify()  Time elapsed: 0 sec  <<< FAILURE!
com.dtp.common.ex.DtpException: Cannot find a specified dtpExecutor, name: dtpExecutor14
	at com.dtp.core.DtpRegistry.getDtpExecutor(DtpRegistry.java:119)
	at com.dtp.test.core.thread.ScheduledDtpExecutorTest.testSubNotify(ScheduledDtpExecutorTest.java:47)
Running com.dtp.test.core.thread.jmh_generated.DtpExecutorBenchmarkTest_normal_jmhTest
Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.015 sec
Running com.dtp.test.core.thread.jmh_generated.DtpExecutorBenchmarkTest_test_jmhTest
Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running com.dtp.test.core.spring.DtpBaseBeanConfigurationTest
Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Results :
Failed tests:   com.dtp.test.core.thread.DtpExecutorTest.testRunTimeout(): Cannot find a specified dtpExecutor, name: testRunTimeoutDtpExecutor
  com.dtp.test.core.thread.DtpExecutorTest.testQueueTimeout(): Cannot find a specified dtpExecutor, name: testQueueTimeoutDtpExecutor
  com.dtp.test.core.thread.DtpExecutorTest.testRejectedQueueTimeoutCancel(): Cannot find a specified dtpExecutor, name: testRejectedQueueTimeoutCancelDtpExecutor
  com.dtp.test.core.thread.ScheduledDtpExecutorTest.testScheduleJre8Bug(): Cannot find a specified dtpExecutor, name: dtpExecutor13
  com.dtp.test.core.thread.ScheduledDtpExecutorTest.testSubNotify(): Cannot find a specified dtpExecutor, name: dtpExecutor14
Tests run: 5, Failures: 5, Errors: 0, Skipped: 0
```

**Comment by KamToHung** [comment]
我这边试了下没问题，mvn clean后再试下

**Comment by ruoan777** [comment]
> 我这边试了下没问题，mvn clean后再试下

本地跑了下报错的单个ut确实是可以的，但是全部一起跑就不行。另外我找了下[最新的合并记录](https://github.com/dromara/dynamic-tp/pull/202/checks)，也是失败的哎。

![image](https://user-images.githubusercontent.com/24860652/230555701-e40d8352-eeb6-41df-a7cf-05e86a749abd.png)

**Comment by KamToHung** [comment]
> > 我这边试了下没问题，mvn clean后再试下
> 
> 本地跑了下报错的单个ut确实是可以的，但是全部一起跑就不行。另外我找了下[最新的合并记录](https://github.com/dromara/dynamic-tp/pull/202/checks)，也是失败的哎。
> 
> ![image](https://user-images.githubusercontent.com/24860652/230555701-e40d8352-eeb6-41df-a7cf-05e86a749abd.png)

好的，我这边处理处理

**Comment by KamToHung** [comment]
done
