### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by highsense** [dromara/dynamic-tp#260]
**首先感谢您使用 DynamicTp，如果使用过程中有任何问题，请按照下述模板反馈问题，建议使用 Markdown 语法**。

### 版本信息

- Jdk版本：11
- SpringBoot版本：2.6.5
- DynamicTp版本：1.1.0
- 配置中心版本：1.1.0

### 问题描述

文字描述、截图、粘代码方式

- 配置文件：
- 代码使用步骤：
在项目中使用默认配置的dp，大负载运行几个小时候，开始抛出NullPointerException

- 报错信息：
17:07:10.192 4701836 [dynamic-executor-1] ERROR c.d.c.t.NamedThreadFactory  thread Thread[dynamic-executor-1,5,main] throw exception {}
java.lang.NullPointerException: null
        at com.dtp.common.queue.VariableLinkedBlockingQueue.extract(VariableLinkedBlockingQueue.java:172)
        at com.dtp.common.queue.VariableLinkedBlockingQueue.take(VariableLinkedBlockingQueue.java:438)
        at java.base/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

- 猜测可能原因：
`com.dtp.common.queue.VariableLinkedBlockingQueue` 该类存在并发修改问题，运行过程中的并发修改导致改类的head.next为null，所以抛出空指针

### 复现步骤

1. xxx
2. xxx

### 其他信息

1. xxx
2. xxx

**Comment by 1132032434** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by highsense** [comment]
> 1.1.3及之前版本VariableLinkedBlockingQueue代码是基于jdk1.8前的LinkedBlockingQueue，貌似会有性能问题；1.1.4将升级到jdk1.8里的LinkedBlockingQueue，可以在留意看看

hmmm，升级之后会解决这个NPE问题不？我现在在配置里把queue改成了ArrayBlockQueue，暂时没有这个问题了

**Comment by yanhom1314** [comment]
> > 1.1.3及之前版本VariableLinkedBlockingQueue代码是基于jdk1.8前的LinkedBlockingQueue，貌似会有性能问题；1.1.4将升级到jdk1.8里的LinkedBlockingQueue，可以在留意看看
> 
> hmmm，升级之后会解决这个NPE问题不？我现在在配置里把queue改成了ArrayBlockQueue，暂时没有这个问题了

可能会，不太确定，因为我没复现出这个问题。。。
