### ISSUE TITLE
NPE: Cannot invoke "java.util.List.stream()" because "executors" is null

### ISSUE THREAD

**Issue by chaoyoung** [dromara/dynamic-tp#480]
### 版本信息

- Jdk版本：21
- SpringBoot版本：3.3.4
- DynamicTp版本：1.1.8-3.x
- 配置中心类型：Nacos
- 配置中心版本：2.2.3

### 问题描述
未配置executors时，启动报错：
```
2024-09-25 16:45:50.071 ERROR [main] o.s.boot.SpringApplication :859 - Application run failed
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "executors" is null
	at org.dromara.dynamictp.core.DtpRegistry.onContextRefreshedEvent(DtpRegistry.java:345)
	at org.dromara.dynamictp.common.spring.OnceApplicationContextEventListener.onApplicationEvent(OnceApplicationContextEventListener.java:50)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:185)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:178)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:156)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:452)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:385)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:993)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:628)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:335)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1363)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1352)
	at com.xxx.yyy.Application.main(Application.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:102)
	at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:64)
	at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:40)
```

- 配置文件：
- 引入的依赖：
- 代码使用步骤：
- 报错信息：
- 猜测可能原因：
<img width="962" alt="image" src="https://github.com/user-attachments/assets/1c06c6bd-444f-43e3-a144-22f05c74a8e5">

### 复现步骤

1. xxx
2. xxx

### 其他信息

1. xxx
2. xxx

**Comment by yanhom1314** [comment]
1.1.8 版本 executor 为空时有这个npe bug，建议不要用，用即将发布的1.1.9
