### ISSUE TITLE
Undertow容器使用动态线程配置时启动异常

### ISSUE THREAD

**Issue by kvchoi** [dromara/dynamic-tp#503]
**首先感谢您使用 DynamicTp，如果使用过程中有任何问题，请按照下述模板反馈问题，请使用 Markdown 语法**。

### 版本信息

- Jdk版本：17
- SpringBoot版本： 2.7.18
- DynamicTp版本：1.1.9.1
- 配置中心类型：无
- 配置中心版本：无

### 问题描述
启动异常

文字描述、截图、粘代码方式

2024-11-11 23:54:07.618 [ERROR] [o.s.boot.SpringApplication] Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'undertowTpHandler' defined in class path resource [org/dromara/dynamictp/starter/adapter/webserver/autocconfigure/WebServerTpAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.dromara.dynamictp.starter.adapter.webserver.undertow.UndertowDtpAdapter]: Factory method 'undertowTpHandler' threw exception; nested exception is java.lang.IncompatibleClassChangeError: class org.dromara.dynamictp.starter.adapter.webserver.undertow.EnhancedQueueExecutorProxy cannot inherit from final class org.jboss.threads.EnhancedQueueExecutor
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:481)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:213)
	at org.springframework.context.event.AbstractApplicationEventMulticaster.retrieveApplicationListeners(AbstractApplicationEventMulticaster.java:264)
	at org.springframework.context.event.AbstractApplicationEventMulticaster.getApplicationListeners(AbstractApplicationEventMulticaster.java:221)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:140)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:133)
	at org.springframework.context.support.AbstractApplicationContext.registerListeners(AbstractApplicationContext.java:892)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:588)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:409)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1289)
	at com.bytesus.cps.CpsServerApplication.main(CpsServerApplication.java:23)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.dromara.dynamictp.starter.adapter.webserver.undertow.UndertowDtpAdapter]: Factory method 'undertowTpHandler' threw exception; nested exception is java.lang.IncompatibleClassChangeError: class org.dromara.dynamictp.starter.adapter.webserver.undertow.EnhancedQueueExecutorProxy cannot inherit from final class org.jboss.threads.EnhancedQueueExecutor
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:648)
	... 22 common frames omitted
Caused by: java.lang.IncompatibleClassChangeError: class org.dromara.dynamictp.starter.adapter.webserver.undertow.EnhancedQueueExecutorProxy cannot inherit from final class org.jboss.threads.EnhancedQueueExecutor
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at org.dromara.dynamictp.starter.adapter.webserver.autocconfigure.WebServerTpAutoConfiguration.undertowTpHandler(WebServerTpAutoConfiguration.java:60)
	at org.dromara.dynamictp.starter.adapter.webserver.autocconfigure.WebServerTpAutoConfiguration$$EnhancerBySpringCGLIB$$53ff57a2.CGLIB$undertowTpHandler$2(<generated>)
	at org.dromara.dynamictp.starter.adapter.webserver.autocconfigure.WebServerTpAutoConfiguration$$EnhancerBySpringCGLIB$$53ff57a2$$FastClassBySpringCGLIB$$3d88cd6.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at org.dromara.dynamictp.starter.adapter.webserver.autocconfigure.WebServerTpAutoConfiguration$$EnhancerBySpringCGLIB$$53ff57a2.undertowTpHandler(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 23 common frames omitted

**Comment by yanhom1314** [comment]
jdk17 用 1.1.9.1-3.x版本，dynamic-tp-spring-boot-starter-adapter-webserver依赖放在spring-boot-starter-undertow依赖之前
