### ISSUE TITLE
执行scheduledFuture cancel报错

### ISSUE THREAD

**Issue by HaoClassmate** [dromara/dynamic-tp#515]
**首先感谢您使用 DynamicTp，如果使用过程中有任何问题，请按照下述模板反馈问题，请使用 Markdown 语法**。

### 版本信息

- Jdk版本：
- SpringBoot版本：
- DynamicTp版本：1.1.91
- 配置中心类型：
- 配置中心版本：

### 问题描述

文字描述、截图、粘代码方式

- 配置文件：
- 引入的依赖：
- 代码使用步骤：
```
 @Resource
   private ScheduledDtpExecutor scheduledDtpExecutor;

    @PostConstruct
    public void init() {
        log.info("init");

        ScheduledFuture<?> scheduledFuture = scheduledDtpExecutor.scheduleWithFixedDelay(() -> log.info("scheduledDtpExecutor"), 0, 1000, TimeUnit.MILLISECONDS);

        scheduledFuture.cancel(false);
    }
```
- 报错信息：

```
java.util.concurrent.CancellationException: null
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:121)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.dromara.dynamictp.common.util.ExecutorUtil.tryPrintError(ExecutorUtil.java:55)
	at org.dromara.dynamictp.common.util.ExecutorUtil.tryExecAfterExecute(ExecutorUtil.java:41)
	at org.dromara.dynamictp.core.support.ScheduledThreadPoolExecutorProxy.afterExecute(ScheduledThreadPoolExecutorProxy.java:97)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

```

- 猜测可能原因： 
  ExecutorUtil.tryPrintError调用future.get()时候因为任务已经cancel，导致报错

### 复现步骤

1. scheduledDtpExecutor.scheduleWithFixedDelay
2.   scheduledFuture.cancel(false);

**Comment by KamToHung** [comment]
已处理#516
