### ISSUE TITLE
问题反馈模板

### ISSUE THREAD

**Issue by yanhom1314** [dromara/dynamic-tp#60]
首先感谢使用 DynamicTp，如果使用过程中有任何问题，请按照下述模板反馈问题，建议使用 Markdown 语法

## 参考格式
+ SpringBoot 版本
+ DynamicTp 版本
+ 配置中心类型
+ 问题描述
+ 使用截图（配置中心配置文件、项目配置文件、代码使用、报错信息等）

**Comment by a805814077** [comment]
SpringBoot 版本：v2.3.6.RELEASE
DynamicTp 版本：1.0.8
配置中心类型：nacos
问题描述：
请问，动态线程参数只能改小不能改大吗，我改小会有这个ERROR，有改大的办法吗
app=dp-service th=[com.alibaba.nacos.client.Worker.longPolling.fixed-nacos.dhgate.internal_30048-prophet] lv=ERROR class=c.d.c.DtpRegistry msg=DynamicTp refresh, new corePoolSize [4] cannot greater than current maximumPoolSize [1].

**Comment by yanhom1314** [comment]
可以改，这个是jdk的限制，你可以看下jdk11中setCorePoolSize方法，要设置的corePoolSize不能大于当前maximumPoolSize

**Comment by a805814077** [comment]
那就是jdk11里面，想调大的话，得手动改两次nacos配置了。第一次改大maximumPoolSize，第二次再改大corePoolSize了。

**Comment by yanhom1314** [comment]
是这样

**Comment by Ricardo-M-Lu0** [comment]
- SpringBoot 版本：2.3.12.RELEASE
- DynamicTp 版本：1.0.9
- 配置中心类型：Nacos
- 问题描述：使用`java.util.concurrent.ScheduledExecutorService`类型的线程池时，提示bean的类型不匹配
- 报错信息：
```log
Caused by: org.springframework.beans.factory.BeanNotOfRequiredTypeException: Bean named 'scheduledExecutorService' is expected to be of type 'java.util.concurrent.ScheduledExecutorService' but was actually of type 'com.dtp.core.thread.DtpExecutor'
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:399) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:207) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.resolveBeanByName(AbstractAutowireCapableBeanFactory.java:453) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.autowireResource(CommonAnnotationBeanPostProcessor.java:527) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.getResource(CommonAnnotationBeanPostProcessor.java:497) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor$ResourceElement.getResourceToInject(CommonAnnotationBeanPostProcessor.java:650) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.annotation.InjectionMetadata$InjectedElement.inject(InjectionMetadata.java:228) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessProperties(CommonAnnotationBeanPostProcessor.java:318) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	... 37 common frames omitted
```
- 使用代码：
```java
@Configuration
public class ThreadPoolConfig {
    @DynamicTp("scheduledExecutorService")
    @Bean("scheduledExecutorService")
    public ScheduledExecutorService executorService() {
        ScheduledThreadPoolExecutor scheduledThreadPoolExecutor = new ScheduledThreadPoolExecutor(1,
                BasicThreadFactory.builder().namingPattern("task_queue_monitor_%d").daemon(true).build());
        return scheduledThreadPoolExecutor;
    }
}

@Service
public class ScheduleServiceImpl{
    @Resource
    private ScheduledExecutorService scheduledExecutorService;

    public void schedule(){
         scheduledExecutorService.schedule(this::task, 0, TimeUnit.SECONDS);
    }
    private void task(){
         // do something
    }
}
```
